version: '3.1'

services:
  ghost:
    build:
      context: ./
      dockerfile: ghost.dockerfile
    restart: always
    links: 
      - db
    ports:
      - ${SERVER_PORT}:2368
    environment:
      url: ${SERVER_URL}
      NODE_ENV: ${NODE_ENV}
      database__client: ${DB_CLIENT}
      database__connection__host: ${DB_HOST}
      database__connection__database: ${DB_NAME}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET: ${GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET}
    volumes: 
      - ./content/:/var/www/ghost/content/
      - ./config.development.json:/var/www/ghost/config.development.json

  db:
    image: mysql:5.7
    restart: always
    volumes:
        - dbdata:/var/lib/mysql:z
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  dbdata: